// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: MeowletService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartPawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PawId         string                 `protobuf:"bytes,1,opt,name=paw_id,json=pawId,proto3" json:"paw_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	CpuLimit      float64                `protobuf:"fixed64,3,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   float64                `protobuf:"fixed64,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPawRequest) Reset() {
	*x = StartPawRequest{}
	mi := &file_MeowletService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPawRequest) ProtoMessage() {}

func (x *StartPawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MeowletService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPawRequest.ProtoReflect.Descriptor instead.
func (*StartPawRequest) Descriptor() ([]byte, []int) {
	return file_MeowletService_proto_rawDescGZIP(), []int{0}
}

func (x *StartPawRequest) GetPawId() string {
	if x != nil {
		return x.PawId
	}
	return ""
}

func (x *StartPawRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartPawRequest) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *StartPawRequest) GetMemoryLimit() float64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

type StartPawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPawResponse) Reset() {
	*x = StartPawResponse{}
	mi := &file_MeowletService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPawResponse) ProtoMessage() {}

func (x *StartPawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MeowletService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPawResponse.ProtoReflect.Descriptor instead.
func (*StartPawResponse) Descriptor() ([]byte, []int) {
	return file_MeowletService_proto_rawDescGZIP(), []int{1}
}

func (x *StartPawResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopPawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PawId         string                 `protobuf:"bytes,1,opt,name=paw_id,json=pawId,proto3" json:"paw_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPawRequest) Reset() {
	*x = StopPawRequest{}
	mi := &file_MeowletService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPawRequest) ProtoMessage() {}

func (x *StopPawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MeowletService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPawRequest.ProtoReflect.Descriptor instead.
func (*StopPawRequest) Descriptor() ([]byte, []int) {
	return file_MeowletService_proto_rawDescGZIP(), []int{2}
}

func (x *StopPawRequest) GetPawId() string {
	if x != nil {
		return x.PawId
	}
	return ""
}

type StopPawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPawResponse) Reset() {
	*x = StopPawResponse{}
	mi := &file_MeowletService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPawResponse) ProtoMessage() {}

func (x *StopPawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MeowletService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPawResponse.ProtoReflect.Descriptor instead.
func (*StopPawResponse) Descriptor() ([]byte, []int) {
	return file_MeowletService_proto_rawDescGZIP(), []int{3}
}

func (x *StopPawResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_MeowletService_proto protoreflect.FileDescriptor

const file_MeowletService_proto_rawDesc = "" +
	"\n" +
	"\x14MeowletService.proto\x12\x05proto\"~\n" +
	"\x0fStartPawRequest\x12\x15\n" +
	"\x06paw_id\x18\x01 \x01(\tR\x05pawId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1b\n" +
	"\tcpu_limit\x18\x03 \x01(\x01R\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\x01R\vmemoryLimit\",\n" +
	"\x10StartPawResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x0eStopPawRequest\x12\x15\n" +
	"\x06paw_id\x18\x01 \x01(\tR\x05pawId\"+\n" +
	"\x0fStopPawResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x87\x01\n" +
	"\x0eMeowletService\x12;\n" +
	"\bStartPaw\x12\x16.proto.StartPawRequest\x1a\x17.proto.StartPawResponse\x128\n" +
	"\aStopPaw\x12\x15.proto.StopPawRequest\x1a\x16.proto.StopPawResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_MeowletService_proto_rawDescOnce sync.Once
	file_MeowletService_proto_rawDescData []byte
)

func file_MeowletService_proto_rawDescGZIP() []byte {
	file_MeowletService_proto_rawDescOnce.Do(func() {
		file_MeowletService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MeowletService_proto_rawDesc), len(file_MeowletService_proto_rawDesc)))
	})
	return file_MeowletService_proto_rawDescData
}

var file_MeowletService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_MeowletService_proto_goTypes = []any{
	(*StartPawRequest)(nil),  // 0: proto.StartPawRequest
	(*StartPawResponse)(nil), // 1: proto.StartPawResponse
	(*StopPawRequest)(nil),   // 2: proto.StopPawRequest
	(*StopPawResponse)(nil),  // 3: proto.StopPawResponse
}
var file_MeowletService_proto_depIdxs = []int32{
	0, // 0: proto.MeowletService.StartPaw:input_type -> proto.StartPawRequest
	2, // 1: proto.MeowletService.StopPaw:input_type -> proto.StopPawRequest
	1, // 2: proto.MeowletService.StartPaw:output_type -> proto.StartPawResponse
	3, // 3: proto.MeowletService.StopPaw:output_type -> proto.StopPawResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MeowletService_proto_init() }
func file_MeowletService_proto_init() {
	if File_MeowletService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MeowletService_proto_rawDesc), len(file_MeowletService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MeowletService_proto_goTypes,
		DependencyIndexes: file_MeowletService_proto_depIdxs,
		MessageInfos:      file_MeowletService_proto_msgTypes,
	}.Build()
	File_MeowletService_proto = out.File
	file_MeowletService_proto_goTypes = nil
	file_MeowletService_proto_depIdxs = nil
}
