// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: MeowletService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeowletService_StartPaw_FullMethodName = "/proto.MeowletService/StartPaw"
	MeowletService_StopPaw_FullMethodName  = "/proto.MeowletService/StopPaw"
)

// MeowletServiceClient is the client API for MeowletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeowletServiceClient interface {
	StartPaw(ctx context.Context, in *StartPawRequest, opts ...grpc.CallOption) (*StartPawResponse, error)
	StopPaw(ctx context.Context, in *StopPawRequest, opts ...grpc.CallOption) (*StopPawResponse, error)
}

type meowletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeowletServiceClient(cc grpc.ClientConnInterface) MeowletServiceClient {
	return &meowletServiceClient{cc}
}

func (c *meowletServiceClient) StartPaw(ctx context.Context, in *StartPawRequest, opts ...grpc.CallOption) (*StartPawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPawResponse)
	err := c.cc.Invoke(ctx, MeowletService_StartPaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meowletServiceClient) StopPaw(ctx context.Context, in *StopPawRequest, opts ...grpc.CallOption) (*StopPawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopPawResponse)
	err := c.cc.Invoke(ctx, MeowletService_StopPaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeowletServiceServer is the server API for MeowletService service.
// All implementations must embed UnimplementedMeowletServiceServer
// for forward compatibility.
type MeowletServiceServer interface {
	StartPaw(context.Context, *StartPawRequest) (*StartPawResponse, error)
	StopPaw(context.Context, *StopPawRequest) (*StopPawResponse, error)
	mustEmbedUnimplementedMeowletServiceServer()
}

// UnimplementedMeowletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeowletServiceServer struct{}

func (UnimplementedMeowletServiceServer) StartPaw(context.Context, *StartPawRequest) (*StartPawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPaw not implemented")
}
func (UnimplementedMeowletServiceServer) StopPaw(context.Context, *StopPawRequest) (*StopPawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPaw not implemented")
}
func (UnimplementedMeowletServiceServer) mustEmbedUnimplementedMeowletServiceServer() {}
func (UnimplementedMeowletServiceServer) testEmbeddedByValue()                        {}

// UnsafeMeowletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeowletServiceServer will
// result in compilation errors.
type UnsafeMeowletServiceServer interface {
	mustEmbedUnimplementedMeowletServiceServer()
}

func RegisterMeowletServiceServer(s grpc.ServiceRegistrar, srv MeowletServiceServer) {
	// If the following call panics, it indicates UnimplementedMeowletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeowletService_ServiceDesc, srv)
}

func _MeowletService_StartPaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeowletServiceServer).StartPaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeowletService_StartPaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeowletServiceServer).StartPaw(ctx, req.(*StartPawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeowletService_StopPaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeowletServiceServer).StopPaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeowletService_StopPaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeowletServiceServer).StopPaw(ctx, req.(*StopPawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeowletService_ServiceDesc is the grpc.ServiceDesc for MeowletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeowletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MeowletService",
	HandlerType: (*MeowletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPaw",
			Handler:    _MeowletService_StartPaw_Handler,
		},
		{
			MethodName: "StopPaw",
			Handler:    _MeowletService_StopPaw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MeowletService.proto",
}
