// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: MewmasterService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MewmasterService_RegisterCat_FullMethodName  = "/proto.MewmasterService/RegisterCat"
	MewmasterService_CatHeartbeat_FullMethodName = "/proto.MewmasterService/CatHeartbeat"
)

// MewmasterServiceClient is the client API for MewmasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MewmasterServiceClient interface {
	RegisterCat(ctx context.Context, in *RegisterCatsRequest, opts ...grpc.CallOption) (*RegisterCatResponse, error)
	CatHeartbeat(ctx context.Context, in *CatHeartbeatRequest, opts ...grpc.CallOption) (*CatHeartbeatResponse, error)
}

type mewmasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMewmasterServiceClient(cc grpc.ClientConnInterface) MewmasterServiceClient {
	return &mewmasterServiceClient{cc}
}

func (c *mewmasterServiceClient) RegisterCat(ctx context.Context, in *RegisterCatsRequest, opts ...grpc.CallOption) (*RegisterCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCatResponse)
	err := c.cc.Invoke(ctx, MewmasterService_RegisterCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mewmasterServiceClient) CatHeartbeat(ctx context.Context, in *CatHeartbeatRequest, opts ...grpc.CallOption) (*CatHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatHeartbeatResponse)
	err := c.cc.Invoke(ctx, MewmasterService_CatHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MewmasterServiceServer is the server API for MewmasterService service.
// All implementations must embed UnimplementedMewmasterServiceServer
// for forward compatibility.
type MewmasterServiceServer interface {
	RegisterCat(context.Context, *RegisterCatsRequest) (*RegisterCatResponse, error)
	CatHeartbeat(context.Context, *CatHeartbeatRequest) (*CatHeartbeatResponse, error)
	mustEmbedUnimplementedMewmasterServiceServer()
}

// UnimplementedMewmasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMewmasterServiceServer struct{}

func (UnimplementedMewmasterServiceServer) RegisterCat(context.Context, *RegisterCatsRequest) (*RegisterCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCat not implemented")
}
func (UnimplementedMewmasterServiceServer) CatHeartbeat(context.Context, *CatHeartbeatRequest) (*CatHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CatHeartbeat not implemented")
}
func (UnimplementedMewmasterServiceServer) mustEmbedUnimplementedMewmasterServiceServer() {}
func (UnimplementedMewmasterServiceServer) testEmbeddedByValue()                          {}

// UnsafeMewmasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MewmasterServiceServer will
// result in compilation errors.
type UnsafeMewmasterServiceServer interface {
	mustEmbedUnimplementedMewmasterServiceServer()
}

func RegisterMewmasterServiceServer(s grpc.ServiceRegistrar, srv MewmasterServiceServer) {
	// If the following call panics, it indicates UnimplementedMewmasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MewmasterService_ServiceDesc, srv)
}

func _MewmasterService_RegisterCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MewmasterServiceServer).RegisterCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MewmasterService_RegisterCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MewmasterServiceServer).RegisterCat(ctx, req.(*RegisterCatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MewmasterService_CatHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MewmasterServiceServer).CatHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MewmasterService_CatHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MewmasterServiceServer).CatHeartbeat(ctx, req.(*CatHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MewmasterService_ServiceDesc is the grpc.ServiceDesc for MewmasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MewmasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MewmasterService",
	HandlerType: (*MewmasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCat",
			Handler:    _MewmasterService_RegisterCat_Handler,
		},
		{
			MethodName: "CatHeartbeat",
			Handler:    _MewmasterService_CatHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MewmasterService.proto",
}
