// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: MewmasterService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterCatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	TotalCpu      float64                `protobuf:"fixed64,3,opt,name=total_cpu,json=totalCpu,proto3" json:"total_cpu,omitempty"`
	TotalRam      int64                  `protobuf:"varint,4,opt,name=total_ram,json=totalRam,proto3" json:"total_ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCatsRequest) Reset() {
	*x = RegisterCatsRequest{}
	mi := &file_MewmasterService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCatsRequest) ProtoMessage() {}

func (x *RegisterCatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MewmasterService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCatsRequest.ProtoReflect.Descriptor instead.
func (*RegisterCatsRequest) Descriptor() ([]byte, []int) {
	return file_MewmasterService_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCatsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCatsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterCatsRequest) GetTotalCpu() float64 {
	if x != nil {
		return x.TotalCpu
	}
	return 0
}

func (x *RegisterCatsRequest) GetTotalRam() int64 {
	if x != nil {
		return x.TotalRam
	}
	return 0
}

type RegisterCatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCatResponse) Reset() {
	*x = RegisterCatResponse{}
	mi := &file_MewmasterService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCatResponse) ProtoMessage() {}

func (x *RegisterCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MewmasterService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCatResponse.ProtoReflect.Descriptor instead.
func (*RegisterCatResponse) Descriptor() ([]byte, []int) {
	return file_MewmasterService_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CatHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      int64                  `protobuf:"varint,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatHeartbeatRequest) Reset() {
	*x = CatHeartbeatRequest{}
	mi := &file_MewmasterService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatHeartbeatRequest) ProtoMessage() {}

func (x *CatHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MewmasterService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*CatHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_MewmasterService_proto_rawDescGZIP(), []int{2}
}

func (x *CatHeartbeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatHeartbeatRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *CatHeartbeatRequest) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

type CatHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatHeartbeatResponse) Reset() {
	*x = CatHeartbeatResponse{}
	mi := &file_MewmasterService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatHeartbeatResponse) ProtoMessage() {}

func (x *CatHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MewmasterService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*CatHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_MewmasterService_proto_rawDescGZIP(), []int{3}
}

func (x *CatHeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_MewmasterService_proto protoreflect.FileDescriptor

const file_MewmasterService_proto_rawDesc = "" +
	"\n" +
	"\x16MewmasterService.proto\x12\x05proto\"s\n" +
	"\x13RegisterCatsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1b\n" +
	"\ttotal_cpu\x18\x03 \x01(\x01R\btotalCpu\x12\x1b\n" +
	"\ttotal_ram\x18\x04 \x01(\x03R\btotalRam\"/\n" +
	"\x13RegisterCatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x13CatHeartbeatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x03R\bramUsage\":\n" +
	"\x14CatHeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xa2\x01\n" +
	"\x10MewmasterService\x12E\n" +
	"\vRegisterCat\x12\x1a.proto.RegisterCatsRequest\x1a\x1a.proto.RegisterCatResponse\x12G\n" +
	"\fCatHeartbeat\x12\x1a.proto.CatHeartbeatRequest\x1a\x1b.proto.CatHeartbeatResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_MewmasterService_proto_rawDescOnce sync.Once
	file_MewmasterService_proto_rawDescData []byte
)

func file_MewmasterService_proto_rawDescGZIP() []byte {
	file_MewmasterService_proto_rawDescOnce.Do(func() {
		file_MewmasterService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MewmasterService_proto_rawDesc), len(file_MewmasterService_proto_rawDesc)))
	})
	return file_MewmasterService_proto_rawDescData
}

var file_MewmasterService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_MewmasterService_proto_goTypes = []any{
	(*RegisterCatsRequest)(nil),  // 0: proto.RegisterCatsRequest
	(*RegisterCatResponse)(nil),  // 1: proto.RegisterCatResponse
	(*CatHeartbeatRequest)(nil),  // 2: proto.CatHeartbeatRequest
	(*CatHeartbeatResponse)(nil), // 3: proto.CatHeartbeatResponse
}
var file_MewmasterService_proto_depIdxs = []int32{
	0, // 0: proto.MewmasterService.RegisterCat:input_type -> proto.RegisterCatsRequest
	2, // 1: proto.MewmasterService.CatHeartbeat:input_type -> proto.CatHeartbeatRequest
	1, // 2: proto.MewmasterService.RegisterCat:output_type -> proto.RegisterCatResponse
	3, // 3: proto.MewmasterService.CatHeartbeat:output_type -> proto.CatHeartbeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MewmasterService_proto_init() }
func file_MewmasterService_proto_init() {
	if File_MewmasterService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MewmasterService_proto_rawDesc), len(file_MewmasterService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MewmasterService_proto_goTypes,
		DependencyIndexes: file_MewmasterService_proto_depIdxs,
		MessageInfos:      file_MewmasterService_proto_msgTypes,
	}.Build()
	File_MewmasterService_proto = out.File
	file_MewmasterService_proto_goTypes = nil
	file_MewmasterService_proto_depIdxs = nil
}
