syntax = "proto3";
option go_package = "./pb";
package proto;

service MewmasterService {
  rpc RegisterCat(RegisterCatsRequest) returns (RegisterCatResponse);
  rpc CatHeartbeat(CatHeartbeatRequest) returns (CatHeartbeatResponse);
}

message RegisterCatsRequest {
  string name = 1;
  string ip = 2;
  double total_cpu = 3;
  int64 total_ram = 4;

}
message RegisterCatResponse {
  bool success = 1;
}

message CatHeartbeatRequest{ //ADD STATUS, LAST HEARTBEAT(if needed), and defintly need
  string name = 1;
  double cpu_usage = 2;
  int64 ram_usage = 3;
}

message CatHeartbeatResponse {
  bool acknowledged = 1;
}